### ISSUE TITLE
When using a soft break within an indented paragraph, the indentation gets removed when loading said paragraph into the editor

### ISSUE THREAD

**Issue by brenner-company** [lblod/ember-rdfa-editor#1076]
Environments where this bug was reproduced:

**OS:** MacOS
**Browser:** Chrome & Firefox

Package version this was tested on: `8.1.0`

Steps to reproduce: 
- Open the dummy application.
- Input some text and indent it using the indentation tool within the toolbar.
- Add a soft break to the indented text using `shift + enter` and add some more text.
- Reload the dummy application.
- The indentation (and thus the `data-indentation-level` value) gets removed.

Remark: When not using a soft break within a paragraph, the indentation works as expected.

Example video:

https://github.com/lblod/ember-rdfa-editor/assets/18174827/c4cc702a-dd89-402f-b2df-5dd9ddeee8f1

**Comment by elpoelma** [comment]
This bug should be fixed in [8.2.0](https://github.com/lblod/ember-rdfa-editor/releases/tag/v8.2.0)
