### ISSUE TITLE
Focus issue: je geraakt vast als je naar het veld tabt

### ISSUE THREAD

**Issue by Wolfr** [lblod/ember-rdfa-editor#30]
Vanaf je in de editor zit met je tab focus, kan je niet verder focussen naar een volgend veld. Je zit als het ware gevangen in de editor met je focus. 

## Steps to reproduce

1. In een formulier met een aantal velden, probeer door de velden de tabben
2. Wanneer je het veld met de rdfa-editor tegenkomt, zit je vast, en moet je naar je muis grijpen (indien beschikbaar) om verder te kunnen.

(getest met versie: "@lblod/ember-rdfa-editor": "0.39.0")

**Comment by nvdk** [comment]
The latest ember-rdfa-editor (0.41.0-rc1.3) introduced a new behaviour which may offer a suitable workaround, pressing escape will unfocus the editor allowing you to tab to the next focusable element.
