### ISSUE TITLE
Plakken werkt niet

### ISSUE THREAD

**Issue by Wolfr** [lblod/ember-rdfa-editor#31]
Als ik tekst probeer te plakken, dan werkt het niet. Nochtans staat de feature flag aan:

```
    featureFlags: {
      'editor-html-paste': true,
    },
```

Het werkt niet met ⌘+V en ook niet met het rechterklik context menu "plakken".

## Steps to reproduce

1. Add something to your pasteboard
2. Try to paste something into the editor

## Expected result

The content of the pasteboard shows up.

**Comment by Wolfr** [comment]
Vorige was test met 0.39.

Als ik tekst probeer te plakken, moet ik soms 2 keer op plakken drukken. Maar het werkt over het algemeen wel terug beter met 0.40rc1.1 (heb toch de indruk).

**Comment by cecemel** [comment]
There have been issues with pasting from PDF indeed. This should have been fixed in 0.40rc1.2.
Could you have a look at this version?
thx

**Comment by Wolfr** [comment]
Ben in our team is going to test this.

**Comment by BenjaminDendas** [comment]
Copy-pasten lijkt te werken.. er is mij echter wel één ding opgevallen. Direct pasten na een andere actie werkt niet, pas wanneer je opnieuw in het tekstveld klikt, paste hij de content.. Hij lijkt de focus van de omgeving te verliezen terwijl de cursor wel blijft flikkeren.

**Getest op:**
Systeem: Macbook Pro
OS: Catalina 
Versie: 10.15.6

**REPRODUCE:**
- Klik in de editor en paste de content
- Doe een CMD A om alles te selecteren en verwijder alles met backspace
- Doe een CMD V om de content terug te pasten.. **dit werkt niet**.
