### ISSUE TITLE
Na het plakken staat je cursor voor de tekst, in plaats van achter de tekst

### ISSUE THREAD

**Issue by Wolfr** [lblod/ember-rdfa-editor#32]
Na een plak-actie staat je cursor voor de tekst, in plaats van achter de tekst.

Normaal als je plakt (eender waar in Windows/Mac) staat je cursor achter de tekst die je net geplakt hebt.

In de rfda-editor staat de tekst ervoor.

Getest met versie: `0.40.0-rc1.1`.

**Comment by nvdk** [comment]
Dit zou beter moeten zijn met v0.42.0-rc1.6 (verwacht finale v0.42.0 ergens volgende week)

**Comment by nvdk** [comment]
v0.42.0 has been released and fixes this issue. feel free to open a new issue in case there are any issues.
