### ISSUE TITLE
Feature request to enable adding custom toolbar buttons in plugins.

### ISSUE THREAD

**Issue by Dexagod** [lblod/ember-rdfa-editor#34]
I am currently working on a [plugin for the editor](https://github.com/Dexagod/rdfa-editor-citation-preview-plugin), that allows users to motivate a selected section of text with an external source.
Currently, by following the documentation, plugins access events through their execute method, where they can match patterns in the text to execute some plugin logic (such as the date plugin matching a written date, or the dbpedia plugin matching the "dbp:" prefix.)

As the RDFa-editor handles toolbar buttons, it would be useful if plugins could add their own toolbar button(s), and receive the events of these buttons.
This feature would provide users of the editor with a more straightforward interface with their installed plugins, instead of having to remember the exact prefix string to execute the functionality of a certain plugin.

Concretely, adding this feature requires a new method for the editor, for example:
```
editor.addToolbarButton(eventName: string, pathToIcon: path)
```
that adds a new button to the toolbar, using the passed icon (or another way that can be used to pass an icon to the toolbar).

Secondly, the event of this button click should be passed to the plugin.
This could make use of the already existing ```execute``` interface, but needs a way to distinguish the button event from different buttons and from text updates. This could be using an optional ```eventName``` parameter for example, as this does not break compatibility

An example of an implementation of this feature could be:
```
export default Service.extend({
  init(){
    this._super(...arguments);
    this.get('editor').addToolbarButton('myPluginEvent', 'myPluginIconPath') // If you can access the editor in the init method
  }

 execute: task(function * (hrId, contexts, hintsRegistry, editor, eventName) { 
    if (eventName === 'myPluginEvent') {
        selectedText = editor.currentSelection()
        // Handle selected text
    } else {
        // Regular plugin  behavior
    } 
  })
})
```

I currently have not enough experience with Ember and the RDFa-editor to create a pull request by myself, 
but if there is interest for this feature I am certainly willing to help.

Kind regards,
Ruben

**Comment by nvdk** [comment]
the input is much appreciated @Dexagod . We definitely want to make the toolbar more dynamic in the future, but are currently focused on core editor behaviour (backspace, delete, ...) so I doubt we'll get to a clean API for this case soon.  

You could try out an undocumented API for plugins that might suit your use case. It's been in use for about 2 years now so it's unlikely to be removed or changed. let us know if this is the route you'll take, so we can keep backwards compatibility in mind if it does need to change.

A plugins service can implement the suggestHints callback. This is triggered when a user pushes the `add annotation` button. The callbacks has two parameters. The first is the rdfaBlocks of the current selection (what was previously called "contexts"). The second is an api for the editor, that allows you to do updates.

```
import Service from '@ember/service';

export default class RdfaEditorSamplePluginService extends Service {
  /**
   * @property rdfaBlocks rdfaBlocks for the current selection
   * @property editor
   */
  async suggestHints(rdfaBlocks, editor) {
    return [{component: 'annotate-text', info: { editor }}];
  }
}

```

in the component you could do the following:
```
import Component from '@glimmer/component';
import { action } from '@ember/object';

export default class AnnotateTextComponent extends Component {
  get editor() {
    return this.args.info.editor;
  }

  @action
  async insert(annotation) {
    const selection = this.editor.selectCurrentSelection();
    this.editor.update(selection, { set: { property: 'http://purl.org/dc/terms/description'}});
    this.args.closeHints();
  }

  @action
  closeHints() {
    this.args.closeHints();
  }
}
```

with a template like this
```
<div>
<button {{on "click" this.insert}}>annotate as description</button> <button {{on "click" this.closeHints}}>close</button>
</div>

```
If useful the sample plugin is available here: https://github.com/nvdk/ember-rdfa-editor-sample-plugin

known issues:
- probably broken on empty selection (e.g. a caret), assumes text is selected.
- some selections run into an error in ember-rdfa-editor <= 0.40.0. It seems its not always splitting text nodes correctly when required. This is fixed on the dev branch of ember-rdfa-editor and should be in the next release of ember-rdfa-editor.
