### ISSUE TITLE
delete after delete removes character too many

### ISSUE THREAD

**Issue by MikiDi** [lblod/ember-rdfa-editor#39]
Step to reproduce (`0.41.0-rc1.2`):
- Open a fresh editor
- Paste or type `test delete handler`
- double-click the word `delete` to select it
- press the [delete] key on you keyboard
- press [delete] once more to remove a space character

You should now end up with `test andler` instead of `test handler`. Note that if you move your cursor back and forth before pressing [delete] the second time, this issue doesn't come up.

**Comment by nvdk** [comment]
going to close this, since we don't have a delete handler anymore atm and the new one will work quite differently
