### ISSUE TITLE
Feature request: addition of super- and subscript text styles

### ISSUE THREAD

**Issue by brenner-company** [lblod/ember-rdfa-editor#404]
Within the current project I'm working on there is a request for the addition of super- and subscript text styles such as 'CO<sup>2</sup>' or 'm<sup>2</sup>' together with the corresponding buttons within the toolbar.

Is this something that could be added by either maintainers or, if permitted, me?

**Comment by abeforgit** [comment]
definitely, it should be fairly simple to add

**Comment by brenner-company** [comment]
@abeforgit Thanks! I'll give it a go during our next sprint.

**Comment by abeforgit** [comment]
definitely contact me when you get on it, not sure if this should go in the core or in a plugin

**Comment by brenner-company** [comment]
@abeforgit I'm going to tackle this feature in our current sprint. I think a plugin seems a tad more logical? Does that mean it's also toggle-able through options/config?

**Comment by brenner-company** [comment]
@abeforgit I'll be starting with this today 🤞

Is it an option to add these two types of styling under `showTextStyleButtons` or should maybe look into something like `showExtendedTextStyleButtons`?

**Comment by abeforgit** [comment]
sorry, I'm really not used to checking our github issues. if we add it as a plugin it's already toggle-able so we don't need the extra option
