### ISSUE TITLE
Character duplicating at start of word when using delete or backspace 

### ISSUE THREAD

**Issue by brenner-company** [lblod/ember-rdfa-editor#797]
Environments where this bug was reproduced:

**OS:** MacOS, Windows
**Browser:** Chrome (Firefox **not** afflicted)
**Source application (when copy/paste):** Acrobat Reader, Acrobat Pro, Preview (MacOS), TextEdit (MacOS), PDF viewer (within Chrome)

Installed version(s) of `ember-rdfa-editor`: `3.3.0` (used on production) & `3.7.1` (tested locally)

Steps to reproduce: 
- Copy/paste or type text inside the editor (in the example below, `Lorem ipsum dolor sit amet, consectetur adipiscing elit` from a plain-text TextEdit file)
- Either do the following:
  - Put your cursor after a word (that is followed by at least two words) and start deleting characters (using `delete` key) until you reach the second consecutive word.
  - Put your cursor after a word (that is followed by at least one word) and start using the `backspace` key to delete the last character of that word.
- The first characters of that consecutive word is now duplicated and the two words are now joined as one word.

Example video (the first set is using `delete`, then second is using `backspace`):

https://github.com/lblod/ember-rdfa-editor/assets/18174827/e8714b89-39e0-4f4b-8ec3-20e7989fa8ea

Code usage within our codebase:
- https://github.com/kanselarij-vlaanderen/frontend-kaleidos/blob/development/app/components/web-components/vl-rdfa-editor.hbs
- https://github.com/kanselarij-vlaanderen/frontend-kaleidos/blob/development/app/components/web-components/vl-rdfa-editor.js

**Comment by brenner-company** [comment]
After some further debugging, it seems like this issue is actually a rather specific Chrome bug 😐

If the following criteria are met within Chrome this issue seems to occur:
- You have a element with `contenteditable="true"` on it.
- That element has or inherits (the latter one is important) styling on the `::first-letter` pseudo-element (For example `color: red`), even if it is (re)set to the default browser value (Eg. as a reset after defining it as a base style).

Similar issues also occur when using (or, again, inheriting) different pseudo-element styling (like ::selection) on elements with `contenteditable="true"`.

I think I have a possible solution to fix this within Kaleidos, so I'll go ahead and close this issue.

Sorry for taking up some your time, but thanks for the help!

**Comment by abeforgit** [comment]
that's... kind of insane
thanks for figuring this out and alerting us
