### ISSUE TITLE
Unable to install npm package with command npm install @lblod/ember-rdfa-editor

### ISSUE THREAD

**Issue by inguva-vamsi1** [lblod/ember-rdfa-editor#943]
[2023-08-23T08_07_49_835Z-debug-0.log](https://github.com/lblod/ember-rdfa-editor/files/12416783/2023-08-23T08_07_49_835Z-debug-0.log)
Unable to install npm package with command npm install @lblod/ember-rdfa-editor

Getting an error that 

npm ERR! code ENOENT
npm ERR! syscall spawn git
npm ERR! path git
npm ERR! errno -4058
npm ERR! enoent An unknown git error occurred
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent

Does this have any dependencies needed to be installed 
Currently i have 

"devDependencies": {
        "@microsoft/eslint-plugin-power-apps": "^0.2.6",
        "@types/node": "^18.8.2",
        "@types/powerapps-component-framework": "^1.3.4",
        "@types/react": "^16.14.45",
        "@types/react-dom": "^18.2.7",
        "@typescript-eslint/eslint-plugin": "^5.39.0",
        "@typescript-eslint/parser": "^5.39.0",
        "eslint": "^8.24.0",
        "eslint-plugin-import": "^2.26.0",
        "eslint-plugin-node": "^11.1.0",
        "eslint-plugin-promise": "^6.0.1",
        "pcf-scripts": "^1",
        "pcf-start": "^1",
        "typescript": "^4.8.4"
      }
        
     Please specify the other npm packages that needed to be installed in order
     
     @madnificent @abeforgit Please kindly suggest

**Comment by abeforgit** [comment]
This is an [ember](https://emberjs.com/) addon, and as such cannot be used directly in non-ember projects. 
We provide https://github.com/lblod/frontend-embeddable-notule-editor for use in non-ember projects. It bundles all the needed dependencies along with a few plugins.
